### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by jcfrosty** [Sabayon/sabayon-greeter#4]
package requires pywebkitgtk. without this requirement, greeter fails to load.

**Comment by Enlik** [comment]
Seems to be fixed by https://github.com/Sabayon/sabayon-distro/commit/4f53f3611e3aebe2c4e44fd589eab6daacffc8b5, by the way, please use more accurate commit messages (e.g. it's not a revision bump).

**Comment by Enlik** [comment]
Updated package will be available shortly.
